#pragma checksum "..\..\..\MusicPlayer.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "EDB0DC5E456610BD7467AF77298BB66DF763802F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Telhai.DotNet.PlayerProject;


namespace Telhai.DotNet.PlayerProject {
    
    
    /// <summary>
    /// MusicPlayer
    /// </summary>
    public partial class MusicPlayer : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtStatus;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtCurrentSong;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgCover;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtMetaTitle;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtMetaArtist;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtMetaAlbum;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtFilePath;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnEditSong;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider sliderProgress;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider sliderVolume;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lstLibrary;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\MusicPlayer.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSettings;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.1.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Telhai.DotNet.PlayerProject;component/musicplayer.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MusicPlayer.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.1.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.txtCurrentSong = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.imgCover = ((System.Windows.Controls.Image)(target));
            return;
            case 4:
            this.txtMetaTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.txtMetaArtist = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.txtMetaAlbum = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.txtFilePath = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.BtnEditSong = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\MusicPlayer.xaml"
            this.BtnEditSong.Click += new System.Windows.RoutedEventHandler(this.BtnEditSong_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.sliderProgress = ((System.Windows.Controls.Slider)(target));
            
            #line 30 "..\..\..\MusicPlayer.xaml"
            this.sliderProgress.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Slider_DragStarted);
            
            #line default
            #line hidden
            
            #line 31 "..\..\..\MusicPlayer.xaml"
            this.sliderProgress.PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.Slider_DragCompleted);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 34 "..\..\..\MusicPlayer.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnStop_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 35 "..\..\..\MusicPlayer.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnPlay_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 36 "..\..\..\MusicPlayer.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnPause_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.sliderVolume = ((System.Windows.Controls.Slider)(target));
            
            #line 41 "..\..\..\MusicPlayer.xaml"
            this.sliderVolume.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.SliderVolume_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.lstLibrary = ((System.Windows.Controls.ListBox)(target));
            
            #line 54 "..\..\..\MusicPlayer.xaml"
            this.lstLibrary.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.LstLibrary_MouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 54 "..\..\..\MusicPlayer.xaml"
            this.lstLibrary.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.lstLibrary_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 57 "..\..\..\MusicPlayer.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 58 "..\..\..\MusicPlayer.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnRemove_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BtnSettings = ((System.Windows.Controls.Button)(target));
            
            #line 59 "..\..\..\MusicPlayer.xaml"
            this.BtnSettings.Click += new System.Windows.RoutedEventHandler(this.BtnSettings_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

